config/routes.rb
PortfolioBlog::Application.routes.draw do
  root :to => "posts#index"
  match "new", :to => "posts#new"
  
  resources :posts do
    resources :comments
    resources :tags
  end

  resource :user_session
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post

  attr_accessible :comment_text, :creator_alias, :creator_email
  
  validates_presence_of :comment_text, :length => {:minimum => 1, :maximum => 3000 }
  validates_presence_of :creator_alias, :creator_email
  validates_format_of :creator_email, :with => /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/
  validates_presence_of :post

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_presence_of :title, :length => { :minimum => 1, :maximum => 100 }
  validates_presence_of :text, :length => { :minimum => 1 }

  has_many :comments, :dependent => :destroy
  has_many :post_to_tag_connectors, :dependent => :destroy
  has_many :tags, :through => :post_to_tag_connectors

  def tag_texts=(tag_string)
    post_to_tag_connectors.destroy_all
    tag_array = tag_string.strip.split /, */
    tag_array.each do |tag_string|
      post_to_tag_connectors.build :tag_text => tag_string, :post => self
    end
  end

  def tag_texts
    tags.map{|t| t.text}.join(", ")
  end

end

app/models/post_to_tag_connector.rb
class PostToTagConnector < ActiveRecord::Base

  validates_presence_of :post
  validates_presence_of :tag

  belongs_to :post
  belongs_to :tag

  validates_uniqueness_of :post_id, :scope => :tag_id

  def tag_text=(tag_string)
    self.tag = Tag.find_by_text(tag_string)
    if self.tag.nil?
      self.tag = Tag.new(:text => tag_string)
    end
  end

  def tag_text
    self.tag.text
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  attr_accessible :text

  has_many :post_to_tag_connectors, :dependent => :destroy
  has_many :posts, :through => :post_to_tag_connectors

  validates_presence_of :text
  validates_uniqueness_of :text

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |c|
    c.require_password_confirmation = false
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  before_filter :require_user

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    redirect_to root_path unless logged_in?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :require_user

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    if @comment.save
      redirect_to post_path(@post)
    else
      render :action => :new
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_filter :require_user, :only => [:index, :show]

  def index
    @posts = Post.all :limit => 5, :order => 'id DESC'
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_path
    else
      render :action => :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.attributes = params[:post]
    if @post.save
      redirect_to post_path(@post)
    else
      render :action => :edit
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @tags = @post.tags
  end

  def new
    @post = Post.find(params[:post_id])
    @tag = @post.tags.build
  end

  def create
    @post = Post.find(params[:post_id])
    @tag = @post.tags.build(params[:tag])
    if @tag.save
      redirect_to post_path(@post)
    else
      render :action => :new
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_user, :except => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to root_path
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.haml
%h1 Enter your comment

= form_for :comment, :url => post_comments_path(@post) do |form|
  = form.error_messages

  %p
    = form.label :creator_alias, 'your name'
    = form.text_field :creator_alias

  %p
    = form.label :creator_email, 'email address'
    =form.text_field :creator_email

  %p
    = form.label :comment_text, 'your comment'
    = form.text_area :comment_text

  %p
    = form.submit "post your comment"

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title Elizabeth's Code Blog
    = stylesheet_link_tag :all
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=IM+Fell+English'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica+SC'
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body
    .topbox
      %h1 Elizabeth Codes
    %p.notice= notice
    %p.alert= alert
    = yield
.clear

app/views/posts/_form.html.haml
= form_for @post do |form|
  = form.error_messages

  %p
    = form.label :title, 'title'
    = form.text_field :title

  %p
    = form.label :text, 'text'
    = form.text_area :text

  %p
    = form.label :tag_texts, 'tags'
    = form.text_field :tag_texts

  %p
    = form.submit "post to blog"

app/views/posts/edit.html.haml
%h1 Edit post

= render 'form'

%p= link_to 'Done', @post
%p= link_to 'Back', posts_path

app/views/posts/index.html.haml
.profilepicbox
  = image_tag "headshot.jpg"
  .menubox
    =link_to "about me", root_path
    =link_to "archive", root_path
- @posts.each do |post|
  .transbox
    %h2= link_to post.title, post_path(post)
    %p= post.text
    .tags= post.tag_texts
    =link_to "comment on this post", new_post_comment_path(post)

app/views/posts/new.html.haml
%h1 Create a new post.

= render 'form'

%p= link_to 'forget it', posts_path

app/views/posts/show.html.haml
.transbox
  %h2= @post.title
  %p= @post.text
  .tags= @post.tag_texts
  %p= link_to 'Edit', edit_post_path
  - @post.comments.each do |comment|
    .allpurposedivider
    %h4.creator-alias= comment.creator_alias
    %div= comment.comment_text

app/views/tags/index.html.haml
%ul
  - @tags.each do |tag|
    %li= tag

app/views/tags/new.html.haml
= form_for :tags do |tag_form|
  %p
    = tag_form.label :name, 'Tag:'
    = tag_form.text_field :name

  = unless tag_form.object.nil? || tag_form.object.new_record?
    %p
      = tag_form.label :_destroy, 'Remove:'
      = tag_form.check_box :_destroy

app/views/user_sessions/new.html.haml
= form_for @user_session, :url => user_session_path do |form|
  = form.error_messages
  %p
    = form.label :login
    = form.text_field :login
  %p
    = form.label :password
    = form.password_field :password
  = form.submit "Log In"

app/views/user_sessions/show.html.haml
= form_for @user_session, :url => user_sessions_path do |form|
  = form.error_messages
  %p
    = form.label :username
    = form.text_field :username
  %p
    = form.label :password
    = form.password_field :password
  = form.submit "Log In"